
export const neighborhoodRegionMap = {
    // east
    "Bedok": "east",
    "Changi": "east",
    "Changi Bay": "east",
    "Pasir Ris": "east",
    "Paya Lebar": "east",
    "Tampines": "east",
    "Pulau Tekong": "east",
    "Pulau Ubin": "east",
    // central
    "Bishan": "central",
    "Bukit Merah": "central",
    "Bukit Timah": "central",
    "Geylang": "central",
    "Kallang": "central",
    "Marine Parade": "central",
    "Novena": "central",
    "Queenstown": "central",
    "Southern Islands": "central",
    "Tanglin": "central",
    "Toa Payoh": "central",
    "City": "central",
    // north
    "Central Water Catchment": "north",
    "Lim Chu Kang": "north",
    "Mandai": "north",
    "Sembawang": "north",
    "Simpang": "north",
    "Sungei Kadut": "north",
    "Woodlands": "north",
    "Yishun": "north",
    // north-east
    "Ang Mo Kio": "north",
    "Hougang": "north",
    "North-Eastern Islands": "north",
    "Punggol": "north",
    "Seletar": "north",
    "Sengkang": "north",
    "Serangoon": "north",
    // west
    "Boon Lay": "west",
    "Bukit Batok": "west",
    "Bukit Panjang": "west",
    "Choa Chu Kang": "west",
    "Clementi": "west",
    "Jurong East": "west",
    "Jurong West": "west",
    "Pioneer": "west",
    "Tengah": "west",
    "Tuas": "west",
    "Western Islands": "west",
    "Western Water Catchment": "west",
    "Jalan Bahar": "west",
    "Jurong Island": "west",
    // south
    "Sentosa": "south",
}